---
abstract: 'This module is using RDBMS as KVS.'
author:
  - 'Kazunori Minoda <kazunori@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DB-AsKVS
no_index:
  directory:
    - t
    - inc
requires:
  Cache::Memcached::Fast: 0.21
  DBI: 1.627
  String::CRC32: 1.4
version: 0.02
